rgname                 = "stage-prakhar-rg"
service_principal_name = "stage-prakhar-spn"
keyvault_name          = "stage-prakhar-kv-101"
SUB_ID                 = ""
node_pool_name         = "stagenp"
cluster_name           = "stage-prakhar-cluster"
