rgname                 = "dev-prakhar-rg"
service_principal_name = "dev-prakhar-spn"
keyvault_name          = "dev-prakhar-kv-101"
SUB_ID = ""
cluster_name = "dev-prakhar-cluster"
node_pool_name = "devnp"
